from .common import ApiResponse, ok, fail, PageInfo, PagedResponse, UserDTO, VipInfo
from .auth import (
    WechatLoginIn,
    TokenPair,
    LoginOut,
    RefreshTokenIn,
    LogoutIn,
    ProfileOut,
)
from .vip import (
    VipPlanOut, VipOrderIn, VipOrderOut, VipOrderDetailOut,
    WechatNotifyIn, SimulatePayIn,
)
from .schools import (
    SchoolIn,
    SchoolOut,
    SchoolListItem,
    SchoolMajorOut,
    SchoolDetailOut,
    MajorIn,
    MajorOut,
    ScoreLineIn,
    ScoreLineOut,
    AdmissionStatOut,
)
from .admissions import (
    AdmissionCatalogIn,
    AdmissionCatalogOut,
    AdmissionStatIn,
    AdmissionRatioOut,
    AdmissionRatioDetail,
)
from .reports import (
    ReportIn, ReportOut, ReportListIn,
    RecommendIn, RecommendItem, RecommendOut,
)

__all__ = [
    "ApiResponse",
    "ok",
    "fail",
    "PageInfo",
    "PagedResponse",
    "UserDTO",
    "VipInfo",
    "WechatLoginIn",
    "TokenPair",
    "LoginOut",
    "RefreshTokenIn",
    "LogoutIn",
    "ProfileOut",
    "VipPlanOut",
    "VipOrderIn",
    "VipOrderOut",
    "VipOrderDetailOut",
    "WechatNotifyIn",
    "SimulatePayIn",
    "SchoolIn",
    "SchoolOut",
    "SchoolListItem",
    "SchoolMajorOut",
    "SchoolDetailOut",
    "MajorIn",
    "MajorOut",
    "ScoreLineIn",
    "ScoreLineOut",
    "AdmissionStatOut",
    "AdmissionCatalogIn",
    "AdmissionCatalogOut",
    "AdmissionStatIn",
    "AdmissionRatioOut",
    "AdmissionRatioDetail",
    "ReportIn",
    "ReportOut",
    "ReportListIn",
    "RecommendIn",
    "RecommendItem",
    "RecommendOut",
]
